### ISSUE TITLE
Set up the project structure and create the necessary files and folders.

### ISSUE THREAD

**Issue by Ashokanandhu** [AlphacodelabsDemo/Task_Manager#20]

**Comment by Ashokanandhu** [comment]
complete the folder structure ,and setup front end enviornement setup . so that we can work on our design

task-manager/

├── client/
│   ├── public/
│   │   └── index.html
│   └── src/
│       ├── assets/
│       │   └── images/
│       ├── components/
│       │   ├── common/
│       │   │   ├── Button.js
│       │   │   ├── Input.js
│       │   │   └── ...
│       │   ├── tasks/
│       │   │   ├── TaskList.js
│       │   │   ├── TaskItem.js
│       │   │   └── ...
│       │   ├── authentication/
│       │   │   ├── RegistrationForm.js
│       │   │   ├── LoginForm.js
│       │   │   └── ...
│       │   ├── projectManagement/
│       │   │   ├── ProjectManagement.js
│       │   │   ├── ProjectForm.js
│       │   │   └── ...
│       │   ├── TaskDetails.js
│       │   └── ...
│       ├── pages/
│       │   ├── Home.js
│       │   ├── Login.js
│       │   └── ...
│       ├── services/
│       │   ├── api.js
│       │   └── ...
│       ├── store/
│       │   ├── actions/
│       │   │   ├── taskActions.js
│       │   │   ├── projectActions.js
│       │   │   ├── authActions.js
│       │   │   └── ...
│       │   ├── reducers/
│       │   │   ├── taskReducer.js
│       │   │   ├── projectReducer.js
│       │   │   ├── authReducer.js
│       │   │   └── ...
│       │   ├── types/
│       │   │   ├── taskTypes.js
│       │   │   ├── projectTypes.js
│       │   │   ├── authTypes.js
│       │   │   └── ...
│       │   ├── store.js
│       │   └── ...
│       ├── styles/
│       │   ├── components/
│       │   │   ├── Button.css
│       │   │   ├── Input.css
│       │   │   └── ...
│       │   ├── pages/
│       │   │   ├── Home.css
│       │   │   ├── Login.css
│       │   │   └── ...
│       │   └── ...
│       ├── utils/
│       │   ├── auth.js
│       │   └── ...
│       ├── App.js
│       └── index.js
├── server/
│   ├── controllers/
│   │   ├── authController.js
│   │   ├── taskController.js
│   │   ├── projectController.js
│   │   └── ...
│   ├── models/
│   │   ├── User.js
│   │   ├── Task.js
│   │   ├── Project.js
│   │   └── ...
│   ├── routes/
│   │   ├── authRoutes.js
│   │   ├── taskRoutes.js
│   │   ├── projectRoutes.js
│   │   └── ...
│   ├── middleware/
│   │   ├── authMiddleware.js
│   │   └── ...
│   ├── config/
│   │   └── config.js
│   ├── app.js
│   ├── server.js
│   └── ...
└── README.md

**Comment by Neo9050** [comment]
i have added all the folder structure and installed dependencies in client . please pull the code from [frontend new branch](https://github.com/AlphacodelabsDemo/Task_Manager/tree/frontend)  and work on top of it.
